#!/usr/bin/env node
/**
 * Keep one copy of the shared integration helpers, and give every integration
 * its own so a harness that copies the plugin into a cache still works.
 *
 * Run after editing integrations/_shared/*.mjs:  node tools/sync-shared.mjs
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sharedDir = path.join(repoRoot, "integrations", "_shared");
const integrations = ["claude", "codex", "opencode"];

const files = fs.readdirSync(sharedDir).filter((f) => f.endsWith(".mjs"));
let copied = 0;

for (const name of integrations) {
  const targetDir = path.join(repoRoot, "integrations", name, "scripts");
  fs.mkdirSync(targetDir, { recursive: true });
  for (const file of files) {
    const banner =
      "// Generated by tools/sync-shared.mjs from integrations/_shared/. Edit the source, not this copy.\n";
    const body = fs.readFileSync(path.join(sharedDir, file), "utf8");
    fs.writeFileSync(path.join(targetDir, file), banner + body);
    copied++;
  }
}

process.stdout.write(`synced ${copied} file(s) into ${integrations.length} integration(s)\n`);
